# Generated by Django 5.1 on 2024-12-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_name',
            field=models.CharField(default='<No Name Provided>', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
